# build-and-install.sh を実行するターゲット
build:
	bash build-and-install.sh

# Stream Deck プラグインフォルダを開く
open-p:
	open ~/Library/Application\ Support/com.elgato.StreamDeck/Plugins

# クリーンアップ用（必要なら）
clean:
	rm -rf build/   # buildディレクトリを削除する例
